export const workshop = [
  "BARISHAL WORKSHOP",
  "BIRULIA",
  "BOGURA WORKSHOP",
  "CHITTAGONG WORKSHOP",
  "CUMILLA WORKSHOP",
  "DINAJPUR WORKSHOP",
  "FARIDPUR WORKSHOP",
  "GAZIPUR WORKSHOP",
  "HEAD OFFICE",
  "HOBIGANJ WORKSHOP",
  "JASHORE WORKSHOP",
  "JATRABARI",
  "KHULNA WORKSHOP",
  "KUSHTIA WORKSHOP",
  "MANIKGANJ WORKSHOP",
  "MIRPUR-1",
  "MYMENSINGH WORKSHOP",
  "NARSINGDI",
  "OTHERS",
  "RANGPUR WORKSHOP",
  "SATKHIRA WORKSHOP",
  "SIRAJGANJ WORKSHOP",
  "SONARGAON WORKSHOP",
  "SYLHET WORKSHOP",
  "TANGAIL WORKSHOP",
  "TEJGAON WORKSHOP",
  "THAKURGAON WORKSHOP",
];

export const district = [
  "Dhaka",
  "Faridpur",
  "Gazipur",
  "Gopalganj",
  "Jamalpur",
  "Kishoreganj",
  "Madaripur",
  "Manikganj",
  "Munshiganj",
  "Mymensingh",
  "Narayanganj",
  "Narsingdi",
  "Netrokona",
  "Rajbari",
  "Shariatpur",
  "Sherpur",
  "Tangail",
  "Bogra",
  "Joypurhat",
  "Naogaon",
  "Natore",
  "Nawabganj",
  "Pabna",
  "Rajshahi",
  "Sirajgonj",
  "Dinajpur",
  "Gaibandha",
  "Kurigram",
  "Lalmonirhat",
  "Nilphamari",
  "Panchagarh",
  "Rangpur",
  "Thakurgaon",
  "Barguna",
  "Barisal",
  "Bhola",
  "Jhalokati",
  "Patuakhali",
  "Pirojpur",
  "Bandarban",
  "Brahmanbaria",
  "Chandpur",
  "Chittagong",
  "Comilla",
  "Cox's Bazar",
  "Feni",
  "Khagrachari",
  "Lakshmipur",
  "Noakhali",
  "Rangamati",
  "Habiganj",
  "Maulvibazar",
  "Sunamganj",
  "Sylhet",
  "Bagerhat",
  "Chuadanga",
  "Jessore",
  "Jhenaidah",
  "Khulna",
  "Kushtia",
  "Magura",
  "Meherpur",
  "Narail",
  "Satkhira",
];
