import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DrawerList from "@/components/Drawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Inventory App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-[8vh] w-full bg-orange-400 text-white uppercase flex items-center justify-center font-bold">
          <div className="flex-[3.3]"> {<DrawerList />}</div>
          <div className="flex-[3.3] text-xs lg:text-sm text-center">
            Inventory Management
          </div>
          <div className="flex-[3.3]"></div>
        </div>
        <div className="h-[92vh] w-full">{children}</div>
      </body>
    </html>
  );
}

// import { cookies } from "next/headers";
// import "./globals.css";
// import DrawerList from "@/components/Drawer";

// export const metadata = {
//   title: "Inventory App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({ children }) {
//   const cookieStore = await cookies();
//   const auth = cookieStore.get("auth");
//   if (!auth) {
//     return (
//       <html lang="en">
//         <body>
//           <div className="h-screen flex items-center justify-center ">
//             <a
//               href={"/login"}
//               className="text-white uppercase text-xl bg-black p-4 rounded-md"
//             >
//               Please Login First
//             </a>
//           </div>
//         </body>
//       </html>
//     );
//   }
//   return (
//     <html lang="en">
//       <body>
//         <div className="h-[8vh] w-full bg-orange-400 text-white uppercase flex items-center justify-center font-bold">
//           <div className="flex-[3.3]">{<DrawerList />}</div>
//           <div className="flex-[3.3] text-center">Inventory Management</div>
//           <div className="flex-[3.3]"></div>
//         </div>
//         <div className="h-[92vh] w-full">{children}</div>
//       </body>
//     </html>
//   );
// }
